### ISSUE TITLE
The new `safe-routes@v1.0.0` no longer works in `react-router@v7` 

### ISSUE THREAD

**Issue by yesmeck** [yesmeck/safe-routes#123]
@yesmeck the new `safe-routes@v1.0.0` no longer works in `react-router@v7` (framework mode with file-based routing) due to `$routeId()` input type of route paths (eg: `/blog`) instead of file paths (`routes/blog.tsx`, or `routes/blog/route.tsx`)

_Originally posted by @SutuSebastian in https://github.com/yesmeck/safe-routes/issues/39#issuecomment-2536612843_

**Comment by SutuSebastian** [comment]
That was fast 👀 👏

**Comment by SutuSebastian** [comment]
the `1.0.1` release fixes this, but does not work 100% backwards compatible with `remix-routes`, for example:

If we have a tree of 2 routes:

- `routes/blog.tsx` - has a `loader`
- `routes/blog._index.tsx` - used to remove parent layout and render components/ui

### Issue

`useRouteLoaderData($routeId("routes/blog"))` will throw error, since only `$routeId("routes/blog._index")` exists in generated types.

Not sure if this is intended or it should also take into account `.index` suffixes 🤔

**Comment by yesmeck** [comment]
@SutuSebastian It's a bug.

**Comment by yesmeck** [comment]
@SutuSebastian  try 1.0.2

**Comment by SutuSebastian** [comment]
@yesmeck works wonders, thank u and great job with the library
